name: Publish Documentation

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          VERSION=$(date +%s)
          echo "hi dani"
          echo ${{ secrets.AWS_ACCESS_KEY_ID }}
          echo $TOK
    env:
      TOK: picha
          